import type { WorkflowDefinition } from "./model";

export function structuredBundledWorkflowDefinitions(agentId: string, now = Date.now()): WorkflowDefinition[] {
  return [{
    id: "resume-technical-highlights",
    name: "简历近期技术亮点补充",
    description: "检查工作目录中的代码项目和 Git 记录，找出已有简历尚未体现且有证据支撑的技术亮点。",
    isTemplate: true,
    inputs: [{
      key: "existingResume",
      name: "已有简历内容",
      description: "用于排除简历中已经写过的内容；没有时可以留空。",
      type: "text",
      required: false,
    }],
    nodes: [{
      id: "discover-highlights",
      kind: "agent",
      title: "发现近期技术亮点",
      goal: "从代码与 Git 记录中提炼可用于简历、且现有简历尚未覆盖的近期技术亮点。",
      agentId,
      instructions: [
        "浏览工作目录下的代码项目，识别中间件、架构、性能与明确负责的模块。",
        "检查 Git 提交记录，用代码和提交证据核验候选亮点。",
        "与已有简历逐项比较，删除重复内容。",
        "优先选择能说清问题、技术动作、责任边界和结果的内容。",
      ],
      constraints: [
        "不得编造指标、影响范围或个人职责。",
        "没有足够价值的新增内容时，明确说明原因，不要凑数。",
        "只返回声明的结构化字段，不生成文件。",
      ],
      inputs: [{
        source: "workflow",
        workflowInputKey: "existingResume",
      }],
      outputs: [{
        key: "highlights",
        name: "新增技术亮点",
        description: "有代码或提交证据、且适合补充进简历的候选亮点；每项应写清技术类别、简历表述、证据与可信度。",
        type: "list",
        required: true,
      }, {
        key: "scannedProjects",
        name: "已检查项目",
        description: "本次实际检查过的项目或仓库。",
        type: "list",
        required: true,
      }, {
        key: "noValueReason",
        name: "无新增说明",
        description: "没有值得补充的亮点时说明原因；有亮点时留空。",
        type: "text",
        required: false,
      }],
      acceptanceCriteria: [
        "每条亮点都包含具体证据与责任边界。",
        "候选内容不与已有简历重复。",
        "无新增亮点时，scannedProjects 和 noValueReason 仍完整。",
      ],
    }],
    createdAt: now,
    updatedAt: now,
  }, {
    id: "code-change-review",
    name: "代码变更审查",
    description: "检查当前工作目录中的代码与 Git 变更，给出有证据、可执行且经过复核的审查结论。",
    isTemplate: true,
    inputs: [{
      key: "reviewScope",
      name: "审查范围",
      description: "可选，例如指定模块、分支、提交或重点关注的问题。",
      type: "text",
      required: false,
    }],
    nodes: [{
      id: "inspect-changes",
      kind: "agent",
      title: "检查代码变更",
      goal: "理解当前代码变更的意图、影响范围和潜在风险。",
      agentId,
      instructions: [
        "读取 Git 状态、差异和相关代码，不要只看单个文件。",
        "沿调用链检查行为变化，并关注错误处理、并发、数据一致性和跨平台问题。",
        "每个风险都给出可定位的代码或提交证据。",
      ],
      constraints: [
        "只报告能被代码证据支持的问题。",
        "不要把风格偏好当成缺陷。",
        "不修改文件。",
      ],
      inputs: [{ source: "workflow", workflowInputKey: "reviewScope" }],
      outputs: [{
        key: "changeSummary",
        name: "变更摘要",
        description: "变更目的、涉及模块和关键行为变化。",
        type: "text",
        required: true,
      }, {
        key: "risks",
        name: "风险清单",
        description: "按严重程度排列的问题、影响和建议修复方式。",
        type: "list",
        required: true,
      }, {
        key: "evidence",
        name: "代码证据",
        description: "支撑审查结论的文件、符号、提交或测试证据。",
        type: "list",
        required: true,
      }],
      acceptanceCriteria: [
        "摘要覆盖完整变更范围。",
        "每个风险都能对应到具体证据。",
        "没有发现问题时明确说明已检查的内容。",
      ],
    }, {
      id: "review-findings",
      kind: "review",
      title: "复核审查结论",
      goal: "复核代码审查结论是否准确、完整且有足够证据。",
      agentId,
      instructions: [
        "逐项核对风险与代码证据是否一致。",
        "检查是否遗漏明显的调用链或边界条件。",
        "只有结论可直接交付时才通过。",
      ],
      constraints: ["不得新增没有证据的风险。", "反馈必须具体到需要补查或修正的内容。"],
      targetNodeIds: ["inspect-changes"],
      criteria: [{ key: "evidence", description: "所有风险均有可定位证据。" }, { key: "coverage", description: "审查覆盖了主要行为变化和边界条件。" }],
      onReject: "continue",
      inputs: [
        { source: "node", nodeId: "inspect-changes", outputKey: "changeSummary" },
        { source: "node", nodeId: "inspect-changes", outputKey: "risks" },
        { source: "node", nodeId: "inspect-changes", outputKey: "evidence" },
      ],
      outputs: [{
        key: "verdict",
        name: "复核结论",
        description: "通过时返回 pass，需要重做时返回 revise。",
        type: "text",
        required: true,
      }, {
        key: "criteriaResults",
        name: "逐项检查结果",
        description: "每条复核标准的判断和依据。",
        type: "list",
        required: true,
      }, {
        key: "feedback",
        name: "修改反馈",
        description: "需要重新检查或修正的具体内容；通过时说明通过原因。",
        type: "text",
        required: true,
      }],
      acceptanceCriteria: ["所有复核标准都有明确判断。", "复核结论与证据一致。"],
    }],
    createdAt: now,
    updatedAt: now,
  }, {
    id: "technical-design-from-code",
    name: "基于现有代码生成技术方案",
    description: "先理解当前代码结构，再生成贴合现状、可落地并经过复核的技术方案。",
    isTemplate: true,
    inputs: [{
      key: "requirement",
      name: "需求说明",
      description: "要解决的问题、目标和已知限制。",
      type: "text",
      required: true,
    }],
    nodes: [{
      id: "inspect-architecture",
      kind: "agent",
      title: "理解现有架构",
      goal: "找出与需求相关的代码结构、数据流、扩展点和既有约束。",
      agentId,
      instructions: ["从入口沿调用链浏览相关模块。", "识别可以复用的组件、既有约定和潜在改造边界。", "记录关键判断的代码证据。"],
      constraints: ["只分析与需求相关的部分。", "不得假设不存在的基础设施或接口。", "不修改文件。"],
      inputs: [{ source: "workflow", workflowInputKey: "requirement" }],
      outputs: [{
        key: "architecture",
        name: "现有架构",
        description: "与需求相关的模块、调用链和数据流。",
        type: "text",
        required: true,
      }, {
        key: "extensionPoints",
        name: "可复用扩展点",
        description: "可以复用的组件、接口和约定及其代码位置。",
        type: "list",
        required: true,
      }, {
        key: "constraints",
        name: "实现约束",
        description: "从现有代码和运行环境中确认的约束。",
        type: "list",
        required: true,
      }],
      acceptanceCriteria: ["架构描述可以由代码验证。", "扩展点与需求直接相关。"],
    }, {
      id: "draft-design",
      kind: "agent",
      title: "生成技术方案",
      goal: "基于现有架构设计最小、清晰且可实施的技术方案。",
      agentId,
      instructions: ["说明核心流程、模块职责、数据结构和关键接口。", "明确需要修改的位置和实施顺序。", "列出重要取舍、风险和验证方式。"],
      constraints: ["优先复用现有扩展点。", "避免与需求无关的重构。", "方案必须能够分步实施和验证。"],
      inputs: [
        { source: "workflow", workflowInputKey: "requirement" },
        { source: "node", nodeId: "inspect-architecture", outputKey: "architecture" },
        { source: "node", nodeId: "inspect-architecture", outputKey: "extensionPoints" },
        { source: "node", nodeId: "inspect-architecture", outputKey: "constraints" },
      ],
      outputs: [{
        key: "proposal",
        name: "技术方案",
        description: "包含核心流程、模块职责、数据结构和接口设计的方案正文。",
        type: "text",
        required: true,
      }, {
        key: "implementationSteps",
        name: "实施步骤",
        description: "按依赖顺序排列的代码修改与验证步骤。",
        type: "list",
        required: true,
      }, {
        key: "tradeoffs",
        name: "取舍与风险",
        description: "关键设计取舍、潜在风险和缓解方式。",
        type: "list",
        required: true,
      }],
      acceptanceCriteria: ["每项设计都能映射到现有代码或明确新增点。", "实施步骤没有跳过关键依赖。"],
    }, {
      id: "review-design",
      kind: "review",
      title: "复核技术方案",
      goal: "确认技术方案与现有代码一致，范围合理且可以落地。",
      agentId,
      instructions: ["核对方案是否解决原始需求。", "检查接口、数据流和实施顺序是否自洽。", "发现问题时给出可执行的修改反馈。"],
      constraints: ["不因个人偏好否决可行方案。", "反馈必须指向具体缺口。"],
      targetNodeIds: ["draft-design"],
      criteria: [{ key: "fit", description: "方案符合现有架构和约束。" }, { key: "complete", description: "方案覆盖实现、迁移、测试和风险。" }, { key: "minimal", description: "改动范围与需求相称。" }],
      onReject: "continue",
      inputs: [
        { source: "node", nodeId: "draft-design", outputKey: "proposal" },
        { source: "node", nodeId: "draft-design", outputKey: "implementationSteps" },
        { source: "node", nodeId: "draft-design", outputKey: "tradeoffs" },
      ],
      outputs: [{
        key: "verdict",
        name: "复核结论",
        description: "通过时返回 pass，需要重做时返回 revise。",
        type: "text",
        required: true,
      }, {
        key: "criteriaResults",
        name: "逐项检查结果",
        description: "每条方案标准的判断和依据。",
        type: "list",
        required: true,
      }, {
        key: "feedback",
        name: "修改反馈",
        description: "需要补充或修正的具体方案内容；通过时说明通过原因。",
        type: "text",
        required: true,
      }],
      acceptanceCriteria: ["复核覆盖全部标准。", "结论可以由上游方案和代码事实支持。"],
    }],
    createdAt: now,
    updatedAt: now,
  }, {
    id: "release-readiness-check",
    name: "发布前检查",
    description: "收集当前仓库的 Git 事实，评估发布风险，并由人工确认是否继续。",
    isTemplate: true,
    inputs: [{
      key: "releaseGoal",
      name: "发布目标",
      description: "可选，例如本次准备发布的功能、版本或关注点。",
      type: "text",
      required: false,
    }],
    nodes: [{
      id: "collect-git-facts",
      kind: "script",
      title: "收集 Git 事实",
      goal: "读取当前仓库状态和近期提交，提供可复现的发布检查输入。",
      runtime: "bash",
      source: `#!/usr/bin/env bash
set -euo pipefail
node <<'NODE'
const { execFileSync } = require("node:child_process");
const git = (args) => {
  try { return execFileSync("git", args, { encoding: "utf8" }).trim(); }
  catch { return ""; }
};
const status = git(["status", "--short"]);
const recentCommits = git(["log", "-10", "--pretty=format:%h %s"]);
console.log(JSON.stringify({
  status,
  recentCommits: recentCommits ? recentCommits.split("\\n") : [],
}));
NODE`,
      timeoutSeconds: 30,
      permissions: ["workspace_read", "process"],
      inputs: [],
      outputs: [{
        key: "status",
        name: "工作区状态",
        description: "Git status --short 的结果。",
        type: "text",
        required: true,
      }, {
        key: "recentCommits",
        name: "近期提交",
        description: "最近十条提交的哈希和标题。",
        type: "list",
        required: true,
      }],
      acceptanceCriteria: ["输出来自当前工作目录。", "即使没有变更也返回完整字段。"],
    }, {
      id: "assess-release",
      kind: "agent",
      title: "评估发布状态",
      goal: "结合发布目标、工作区状态和近期提交判断是否具备发布条件。",
      agentId,
      instructions: ["检查未提交变更、提交范围、测试和发布说明。", "区分阻断项、建议项和已通过项。", "给出下一步可执行动作。"],
      constraints: ["不得声称执行过没有证据的测试。", "不执行发布、不提交代码。"],
      inputs: [
        { source: "workflow", workflowInputKey: "releaseGoal" },
        { source: "node", nodeId: "collect-git-facts", outputKey: "status" },
        { source: "node", nodeId: "collect-git-facts", outputKey: "recentCommits" },
      ],
      outputs: [{
        key: "summary",
        name: "发布摘要",
        description: "当前发布范围和准备状态的简要结论。",
        type: "text",
        required: true,
      }, {
        key: "checks",
        name: "检查结果",
        description: "已通过、待确认和未执行的检查项。",
        type: "list",
        required: true,
      }, {
        key: "blockers",
        name: "阻断项",
        description: "发布前必须解决的问题；没有时返回空列表。",
        type: "list",
        required: true,
      }],
      acceptanceCriteria: ["结论区分事实和推断。", "阻断项都有明确处理建议。"],
    }, {
      id: "confirm-release",
      kind: "approval",
      title: "确认是否发布",
      goal: "由用户根据检查结果决定是否继续发布。",
      message: "检查已完成，是否确认继续发布？",
      options: [{ value: "continue", label: "继续", description: "接受当前检查结果并继续后续发布操作。" }, { value: "stop", label: "暂不发布", description: "停止流程，先处理阻断项或补充检查。" }],
      allowComment: true,
      inputs: [
        { source: "node", nodeId: "assess-release", outputKey: "summary" },
        { source: "node", nodeId: "assess-release", outputKey: "checks" },
        { source: "node", nodeId: "assess-release", outputKey: "blockers" },
      ],
      outputs: [{
        key: "decision",
        name: "发布决定",
        description: "用户选择的继续或停止。",
        type: "text",
        required: true,
      }, {
        key: "comment",
        name: "决定说明",
        description: "用户补充的决定背景。",
        type: "text",
        required: false,
      }],
      acceptanceCriteria: ["决定由用户明确确认。"],
    }],
    createdAt: now,
    updatedAt: now,
  }];
}
